### PR TITLE
Fix Primary index name on "oc_social_a2_cache_documts" is too long

### LINKED ISSUE #850: Primary index name on "oc_social_a2_cache_documts" is too long.
**Describe the bug**
 App can not be installed on NC 18.0.0.9 as a error during db-migration occurs.  Seems related to #506 

**To Reproduce**

    1. Go to Social on the Apps-Page of your nextcloud instance
    1. Click on 'Download and enable'
    1. Error message Primary index name on "oc_social_a2_cache_documts" is too long.
    1. App is not installed.

**Expected behavior**
App is installed correctly with needed db

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 72.01
 - Device: Desktop

<details>
<summary>Server details</summary>

**Social app version**:
0.2.101?

**Operating system**:
Debian (Docker)

**Web server:**
Apache 2.4.38

**Database:**
Sqlite3 3.27.2

**PHP version:**
7.3.13

**Nextcloud version:** 
18.0.0 RC2
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[settings] Error: InvalidArgumentException: Primary index name  on "oc_social_a2_cache_documts" is too long. at <<closure>>

 0. /var/www/html/lib/private/DB/MigrationService.php line 484
    OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)
 1. /var/www/html/lib/private/DB/MigrationService.php line 414
    OC\DB\MigrationService->executeStep("0002Date20190506000001", false)
 2. /var/www/html/lib/private/Installer.php line 151
    OC\DB\MigrationService->migrate()
 3. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 443
    OC\Installer->installApp("social")
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["social"], [])
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 6. /var/www/html/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
 9. /var/www/html/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
10. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/enable")
11. /var/www/html/index.php line 38
    OC::handleRequest()

POST /settings/apps/enable
```

#### Browser log
```
Insert your browser log here, this could for example include:

Object { apps: Getter & Setter, categories: Getter & Setter, updateCount: Getter & Setter, loading: Getter & Setter, loadingList: Getter & Setter, … }
 
{…}
​
appId: "social"
​
error: Error
​​
columnNumber: 81448
​​
config: Object { url: "/settings/apps/enable", method: "post", data: "{\"appIds\":[\"social\"],\"groups\":[]}", … }
​​
fileName: "https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5"
​​
isAxiosError: true
​​
lineNumber: 7
​​
message: "Request failed with status code 500"
​​
request: XMLHttpRequest
​​​
mozAnon: false
​​​
mozSystem: false
​​​
onabort: function onabort()
​​​
onerror: function onerror()
​​​
onload: null
​​​
onloadend: null
​​​
onloadstart: null
​​​
onprogress: null
​​​
onreadystatechange: function onreadystatechange()
​​​
ontimeout: function ontimeout()
​​​
readyState: 4
​​​
response: "{\"data\":{\"message\":\"Primary index name  on \\\"oc_social_a2_cache_documts\\\" is too long.\"}}"
​​​
responseText: "{\"data\":{\"message\":\"Primary index name  on \\\"oc_social_a2_cache_documts\\\" is too long.\"}}"
​​​
responseType: ""
​​​
responseURL: "https://nextcloud.domain.com/settings/apps/enable"
​​​
responseXML: null
​​​
status: 500
​​​
statusText: "Internal Server Error"
​​​
timeout: 0
​​​
upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
​​​
withCredentials: false
​​​
<prototype>: XMLHttpRequestPrototype { open: open(), setRequestHeader: setRequestHeader(), send: send(), … }
​​
response: {…}
​​​
config: Object { url: "/settings/apps/enable", method: "post", data: "{\"appIds\":[\"social\"],\"groups\":[]}", … }
​​​
data: Object { data: {…} }
​​​
headers: Object { "cache-control": "no-cache, no-store, must-revalidate", "content-length": "89", "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self'", … }
​​​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​​
status: 500
​​​
statusText: "Internal Server Error"
​​​
<prototype>: Object { … }
​​
stack: "t.exports@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:7:81448\nt.exports@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:45:2592\nt.exports/</p.onreadystatechange@https://nextcloud.domain.com/apps/settings/js/vue-settings-apps-users-management.js?v=e0c431a9-5:7:80381\n"
​​
toJSON: function toJSON()
​​
<prototype>: Object { … }
​
<prototype>: Object { … }
apps.js:38:10

```

</details>

### PR DESCRIPTION
**Pull request by rubo77**
also fixes social_a2_request_queue and social_a2_stream_action name length
new names: social_a2_cache_docum, social_a2_req_queue and social_a2_stream_act

closes #850

Signed-off-by: Ruben Barkow <github@r.z11.de>

* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by rubo77** [comment]
I know, renaming the table in all migration steps is not a good practice.

But this is just my attempt to fix the problem. I tested it and the app works then, at least if you haven't installed any prior version of the app.

Why did this app have worked before in older versions? Or wasn't it tested on MariaDB before?

I am not sure, how the problem could only occur now with the latest update???

**Comment by amiga23** [comment]
You should not change the migration scripts, but add a new migration script, that renames the table.

**Comment by rubo77** [comment]
Sure, that is what I tried first, but it won't work, because, the initial installation of the database already fails, so the migration cannot start

**Comment by rubo77** [comment]
Maybe we should check in each Migration step if the old table is still exist entry name them in each of them before we do the migration

**Comment by rubo77** [comment]
Can someone do this for me please? I don't have the time to learn how the migrations work

**Pull request merged**
