### PR TITLE
[WIP] Notifications timeline (frontend)

### PR DESCRIPTION
**Pull request by violoncelloCH**
* Resolves: #605 
* Target version: master 

### Summary
- [x] navigation entry with a corresponding icon
- [X] display a user block for "{actor} is following you"
- [x] display post blocks for liked / boosted notifications
- [x] correctly display multiple keys ({actor}s etc.)

### CODE REVIEW

**Comment by violoncelloCH** [comment]
image
so this is what it currently looks like...

what I don't get is why it only displays the follow/unfollow button after I went to profile>following/followers... (it only displays a follow button, if one was viewed on profile>follwing/followers; follow and unfollow independently of each other, both need to be somehow loaded there...) any idea @juliushaertl ?

**Comment by daita** [comment]
@juliushaertl can you please have a look to the issue with the 'Follow' button within the Notification timeline ?

**Comment by daita** [comment]
@jancborchardt @violoncelloCH for some readability would be nice to add the icon of the 'action' to the notification (like the star icon for a Like and the Boost icon for a Boost)

**Comment by jancborchardt** [comment]
> @jancborchardt @violoncelloCH for some readability would be nice to add the icon of the 'action' to the notification (like the star icon for a Like and the Boost icon for a Boost)

Yup, totally agree! Should be on the left of the text, flush with the avatar below. Also, the avatars of the people who boosted/liked should be shown left of their names, and the names bolded to highlight them and make clear they are clickable.

**Comment by daita** [comment]
If there is more than 2 (or 3 ?) accounts for a notification, just displays 2 of them, followed by '_and n others_'

**Comment by juliushaertl** [comment]
I'll have a look.

**Comment by StCyr** [comment]
Hello,

I don't see what's wrong with this PR.

Could you please show us on the following screenshot what still needs to be changed?

Untitled

**Comment by jancborchardt** [comment]
@StCyr the basics are done, but icons and some other details as per comment at https://github.com/nextcloud/social/pull/625#issuecomment-513843611 would be nice. :)

**Comment by StCyr** [comment]
> 
> 
> @StCyr the basics are done, but icons and some other details as per comment at [#625 (comment)](https://github.com/nextcloud/social/pull/625#issuecomment-513843611) would be nice. :)

I understand, but not the comments :-)
 
> 
> > @jancborchardt @violoncelloCH for some readability would be nice to add the icon of the 'action' to the notification (like the star icon for a Like and the Boost icon for a Boost)
> 
> Yup, totally agree! Should be on the left of the text, flush with the avatar below. Also, the avatars of the people who boosted/liked should be shown left of their names, and the names bolded to highlight them and make clear they are clickable.

It seems to me that actions are there. Except for the notification "<user> is following you". But, does that make sense to add actions for this kind of notifications?

If, for some reason it does make sense, where do you mean with "Should be on the left of the text, flush with the avatar below."?

Finally, "Also, the avatars of the people who boosted/liked should be shown left of their names, and the names bolded to highlight them and make clear they are clickable."

It seems to me that the avatars are there. What am I missing?

**Comment by StCyr** [comment]
this is how the notification timeline now looks like with my 2 latest commits (note that we don't see the effect of https://github.com/nextcloud/social/pull/625/commits/0dc34afec3a13cc278f6fce3922bc0bda045c247 in this screenshot though): 

image

**Comment by daita** [comment]
Tested, this is great !

- [ ] remove the icons/actions on 'someone followed you' items
- [ ] what will happens if more than 3 accounts like your post ?
- [ ] would it be possible to display the account using the right elements (could be done after merge)
- [ ] rebase

**Comment by StCyr** [comment]
I can't show you what happens when more than 3 accounts like a post because I haven't such notification but here's a screenshot with a modified version of the code ellipsing the notification summary when more than 2 accounts like a post:

image

Your question was very pertinent as there was a bug in my code :-)

**Comment by StCyr** [comment]
>     * would it be possible to display the account using the right elements (could be done after merge)

What do you mean by "the right elements"? UserEntry?

**Comment by StCyr** [comment]
Tested, this is great !

- [x] remove the icons/actions on 'someone followed you' items
- [x] what will happens if more than 3 accounts like your post ?
- [ ] would it be possible to display the account using the right elements (could be done after merge)
- [x] rebase
- [ ] reply function doesn't work in notifications timeline

**Comment by daita** [comment]
Looks like we just remove all action-icons from the notifications timeline and we merge

**Comment by StCyr** [comment]
Should be good now

**Pull request merged**
