### PR TITLE
create object even if it can't be signed

### PR DESCRIPTION
**Pull request by daita**

### CODE REVIEW

**Comment by daita** [comment]
On friday, users encountered some downtime in creating and receiving new Notes. 

To avoid this, caching.

**Comment by daita** [comment]
Caching the content of context url: 

- if file is in appdata, we use it,
- if file is not in appdata, we download it,
- if download is not effective, we get the file from the context/ folder locally.

**Comment by juliushaertl** [comment]
What is the reason we need to dowload them if we have stored them in the repo? Or can they be different on different instances/change later?

**Comment by daita** [comment]
> What is the reason we need to dowload them if we have stored them in the repo? Or can they be different on different instances/change later?

no real reason, this is why it is only downloaded if the file is not in appdata. But still downloadable in case it's not the same version than the one in the app itself.

**Pull request merged**
