### PR TITLE
Make social app compatible with 24

### PR DESCRIPTION
**Pull request by CarlSchwan**
Due to the difference between 23 and 24 in regard to the query builder private API it is a bit tricky to support both 24 and 23 at the same time

### CODE REVIEW

**Comment by skjnldsv** [comment]
It means thre is no version for 22 and 23

**Review by ArtificialOwl — APPROVED** [review]
looks good

**Comment by mirenbz** [comment]
So does this mean it is supposed to work with 24?

**Comment by McSinyx** [comment]
Could a maintainer please tag a release?

**Comment by ArtificialOwl** [comment]
This mean a version for NC24 will be released; just not yet

**Comment by MagicTrevor** [comment]
Looking forward to it.

**Pull request merged**
