### PR TITLE
Make wellknow work with new api

### PR DESCRIPTION
**Pull request by CarlSchwan**
image

### CODE REVIEW

**Comment by CarlSchwan** [comment]
when you fix code by removing 400 lines. Thanks @ChristophWurst for the new API ;)

**Review by violoncelloCH — APPROVED** [review]
code looks good

**Comment by ArtificialOwl** [comment]
You might want to have a look to this https://github.com/nextcloud/server/pull/26178

**Comment by CarlSchwan** [comment]
> You might want to have a look to this [nextcloud/server#26178](https://github.com/nextcloud/server/pull/26178)

yeah, will look into it next ;) Not sure if this is still useful since mastodon removed support for OStatus recently

**Pull request merged**
