### PR TITLE
display boosted posts with an according indication

### PR DESCRIPTION
**Pull request by violoncelloCH**
* Resolves: #324 
* Target version: master 

### Summary
This implements the displaying of reposts (boosted / retooted posts) and displays who has boosted it in a short indication:
image

cc @jancborchardt for design feedback (because I'm not sure what the best way to display this boost message is... maybe right-align the icon and vertically align it to the centre of the text?)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@violoncelloCH looks good! Just 3 details:
- The `username boosted` text could be grey / half-transparent for less focus on that
- The username of the boost doesn’t need to be bold
- The boost icon should move so it’s vertically aligned with the text and right-aligned with the avatar below (see this screenshot):
boosting

**Comment by daita** [comment]
so, I made a test with:

- userA create a new Post (ok)
- userB boost that new Post (ok)
- userC boost the boosted Post. (fail)

On boosting the boosted post, the userC got an error. The link to boost is using the PostId of the Announce, not the Original Post.

**Comment by violoncelloCH** [comment]
@jancborchardt thanks for the feedback! I'll implement your proposal!

@daita are you sure? `TimelineContent.vue`, which does the boosting, should access the cached object and therefore take the id of the cached Note (as long as the backend sends the correct id inside of the cached Note)... Can you double check if it's not the `Type error: ...action is undefined` I'm already working on? (in this case the Note is boosted, but the frontend displays an error, because it can't set the boosted state)

**Comment by daita** [comment]
@violoncelloCH just checked, the postId is an Announce, not a Post. Also, if I click on 'Reply-To' the text 
'In reply to <author of the Boost>' (instead of <author of the Post>) is available above the textarea. Maybe adding both authors (Boost+Post) to the Reply-To list.

**Pull request merged**
