### PR TITLE
show post attachments

### PR DESCRIPTION
**Pull request by StCyr**
Signed-off-by: Cyrille Bollu <cyrpub@bollu.be>

* Resolves: #230
* Target version: master 

### Summary

This PR is working: Images are displayed

Design improvements will be needed though.

### CODE REVIEW

**Comment by StCyr** [comment]
I've created a PostAttachment component to show posts' attachments.

It's currently only able to show images but the idea is that it's extensible.

However, there's an issue: attachments are not sent with posts, rather they contain an url to the attachment. And, obviously, the browser's content security policy blocks the requests to get the attachment at the provided url.

How should I solve this issue? 

Is it what the `Navigation#documentGet` route is for?

**Comment by daita** [comment]
Sorry, you should have pinged me !

Check #352 there is some details and example. Add that if localCopy is set, it means the document is already cached. We still need to decide if caching is a good idea.

**Comment by StCyr** [comment]
This PR is working: Images are displayed

Design improvements will be needed though.

**Comment by daita** [comment]
when running `make`:


/home/maxence/PhpstormProjects/social/src/components/PostAttachment.vue
   3:3   warning  Disallow self-closing on HTML void elements ()  vue/html-self-closing
   3:12  warning  Expected to be enclosed by double quotes              vue/html-quotes
   3:24  warning  Expected to be enclosed by double quotes              vue/html-quotes
  13:10  warning  Prop "id" should define at least its type             vue/require-prop-types

/home/maxence/PhpstormProjects/social/src/components/TimelinePost.vue
   28:81  warning  Attribute ":id" should go before ":key"                        vue/attributes-order
  127:59  error    Unnecessary use of boolean literals in conditional expression  no-unneeded-ternary
  127:71  error    Extra semicolon                                                semi

**Comment by daita** [comment]
only a resized version is cached, the full document will only be available on the remote instance.

**Comment by daita** [comment]
I still have some lint error during `make`:

```
/home/maxence/PhpstormProjects/social/src/components/PostAttachment.vue
   4:4   warning  Disallow self-closing on HTML void elements (<img/>)  vue/html-self-closing
  11:39  error    Extra semicolon                                       semi
  12:32  error    Extra semicolon                                       semi
  22:3   warning  Prop 'attachments' requires default value to be set   vue/require-default-prop
  22:21  error    Unexpected trailing comma                             comma-dangle
```

Also, in package-lock.json, can you use v12.0.1 of twemoji, instead of the 12.1.2 ?

```
	"version": "12.0.1",
			"resolved": "https://registry.npmjs.org/twemoji/-/twemoji-12.0.1.tgz",
			"integrity": "sha512-9jFbDzI4M7wQFX++QQp+t9wHupjL0WdOnE2pNAmJwxchQKw0yRhZD8qm+teHJQdeuvZMu9eJR7RVEpZPPbbYPw==",
```

beside those issues, I like it. maybe having a frame and/or a background ?

**Comment by violoncelloCH** [comment]
@daita is there a way to manually (occ?) create local posts with attachments (so I can test this on my dev setup where I can't follow remote accounts) ? 


regarding the design: instead of using this hooper carousel I would display the attachments in a (masonry? / static aspect ratio) grid and on click on one of the images a nextcloud-vue Modal should open like in the Viewer app, showing a slideshow-like fullscreen view of all attachments 
ref https://github.com/nextcloud/viewer/blob/master/src/views/Viewer.vue
cc @jancborchardt

**Comment by daita** [comment]
There is actually no way to attach something to a Post from the command line.

Your JS thing, would it work on post with n+1 attachments ?

**Comment by daita** [comment]
Also, we will cache 2 version of images. small one that would stays few days, the big one that will be in cache only few hours.

**Comment by jancborchardt** [comment]
Agree with @violoncelloch on the design. We should stick with how Twitter does it for these basic things.

**Comment by daita** [comment]
would be nice to have some footage of the result, because what @violoncelloCH is describing is kind of what the carousel is able to do. You can display a non-limited gallery of resized picture, we just need to add the action of displaying/navigating bigger image from the gallery.

**Comment by daita** [comment]
There is now 2 new routes:

`/document/get/resized`
`/document/public/resized`

`/document/get` returns original size cached version
`/document/get/resized` returns resized version

Also adding a field to database, please run the command below and refresh the app to start migrations:

>      ./occ config:app:set --value '0.2.0' social installed_version

**Comment by StCyr** [comment]
>instead of using this hooper carousel I would prefer to display the attachments in a (masonry? / static aspect ratio) grid

I've try [this one](https://github.com/parys-github/vue-masonry-gallery) (which looks nicer) but it seems buggy: Can't help getting `Module not found: Error: Can't resolve 'vue-masonry-gallery' in '/root/social/src/components'`

I guess they are missing an export :-(

**Comment by daita** [comment]
what about the proposition from @violoncelloCH ? Any link on how to integrate this modal ?

**Comment by StCyr** [comment]
Please validate

**Comment by StCyr** [comment]
Works well on FF/MacOS but doesn't seem to work on FF/iOS (blank pages on my iPhone).

**Comment by itskil** [comment]
Hello there 
I have Nextcloud 17 with social app
But i can’t attach photos to my posts 
Anyone can help me please ??

**Comment by jancborchardt** [comment]
@itskil could you please open a separate issue with more info? Thank you :)

**Pull request merged**
