### PR TITLE
render messages based on the source html

### LINKED ISSUE #328: Sanitize, parse and rewrite content of notes
Right now we just strip all tags from the content and parse the plain text of notes in the frontend. We match `@mentions` and `#hashtags`.

However current implementations work a bit differently and use some html wrapping for mentions and hashtags like this:

## Mastodon

```
<p>
  <span class="h-card">
    <a href="https://mastodon.xyz/@nextcloud" class="u-url mention">
      @<span>nextcloud</span>
    </a>
  </span> 
  <span class="h-card">
    <a href="https://mastodon.social/@meneer" class="u-url mention">
      @<span>meneer</span>
    </a>
  </span>
  Ticking boxes makes me wary; where are the brains? 
  <a href="https://mastodon.nl/tags/gdpr" class="mention hashtag" rel="tag">
    #<span>GDPR</span>
  </a>
</p>
```

## Friendica

```
    "content": "@<span class=\"vcard\"><a href=\"https://test.artificial-owl.com/apps/social/@cult\" class=\"url\" title=\"cult\"><span class=\"fn nickname mention\">cult</span></a></span> #<a href=\"https://squeet.me/search?tag=test\" class=\"tag\" title=\"test\">test</a> ouila",

```

This has the issue that right now, if someone creates a post mentioning
`@nextcloud@mastodon.social and @nextcloud@mastodon.xyz` we will link both to just the local `@nextcloud` account.

So we need to implement the following:
- Properly sanitize the html in content
- Rewrite urls stated in `.u-url.mention` and `.mention.hashtag` to our local routes

Refs: 
- https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes
- https://github.com/tootsuite/mastodon/blob/8069fd636ba14059524303ce76abe2173c4f3d01/app/lib/formatter.rb#L235-L251

### LINKED ISSUE #585: Mentions in toots get linked to local accounts instead of remote information
**Describe the bug**

In the global timeline I have toots with a fair amount of mentions from accounts that I follow remotely.  When those contain @ mentions of other accounts, those are considered to be local accounts and link to /apps/social/@user which doesn't exist instead of /apps/social/@user@server/ which would bring up the profile information for the remote account

### PR DESCRIPTION
**Pull request by icewind1991**
instead of first stripping, and then rebuilding html.

this makes it possible to do proper manipulation on mention and hashtag links.

Works by directly generating Vue elements from the html source, stripping and transforming everything we don't want in the process.

TODO:

- [x] tweemoji
- [x] fix rendering of local activity

Supersedes #667

Fixes #328, fixes #585

### CODE REVIEW

**Comment by icewind1991** [comment]
as a bonus, it now generates vue `router-link`s instead of plain links for mentions and hashtags, meaning that clicking on them no longer trigger a full page reload.

**Comment by daita** [comment]
It seems that it will always replace an account as a local account.

If I create a new Post from an instance of mastodon with multiple mentions from differents instances, the generated links on my instance of Nextcloud are local.

---

# _displayed post_

<p>another test <span class="h-card"><a href="https://test.artificial-owl.com/index.php/apps/social/@cult" class="u-url mention">@<span>cult</span></a></span>  <span class="h-card"><a href="https://social.artificial-owl.com/index.php/apps/social/@cult" class="u-url mention">@<span>cult</span></a></span> <span class="h-card"><a href="https://mastodon.social/@testSocial" class="u-url mention">@<span>testSocial</span></a></span></p>


# _content in database_
```
<p>another test 
<span class="h-card">
 <a href="https://test.artificial-owl.com/index.php/apps/social/@cult" class="u-url mention">@<span>cult</span></a>
</span>
<span class="h-card">
 <a href="https://social.artificial-owl.com/index.php/apps/social/@cult" class="u-url mention">@<span>cult</span></a>
</span> 
<span class="h-card">
 <a href="https://mastodon.social/@testSocial" class="u-url mention">@<span>testSocial</span></a>
</span>
</p>
```

# _result_ in my browser

Selection_015

**Comment by icewind1991** [comment]
Are you sure you've rebuild the js and cleared the cache, that html output looks like the old code to me (see the `linkified` class)

**Comment by daita** [comment]
let me rebuild and upload, i'll keep you updated !

**Comment by daita** [comment]
What about not changing the url for the mention but the hashtags ? It might be good if we keep the mention as it is. The idea is to keep using the remote address for remote accounts and stop using a local redirection

**Comment by icewind1991** [comment]
changed it to keep the remote link for mentions

**Review by daita — APPROVED** [review]
just need a rebase before merge

**Pull request merged**
