### PR TITLE
Update README to include Hubzilla

### PR DESCRIPTION
**Pull request by sunjam**
Added [Hubzilla](https://start.hubzilla.org/page/admin/start) to services list, which is ActivityPub compatible.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good except that there now is a line break. Could you remove that @sunjam?

**Comment by violoncelloCH** [comment]
also DCO is failing because the commit is not signed-off
@sunjam could you please sign your commit? - see https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#sign-your-work
can be done with `git commit --amend -s` for the last commit and then `git push -f` to push the changed commit back to github...

**Comment by jospoortvliet** [comment]
@sunjam any chance you could implement the two changes asked for above? Then this can be merged easily 😘

**Comment by daita** [comment]
d4c7b57

**Pull request closed without merging**
