### PR TITLE
Prevent posting of direct message with no valid recipients

### PR DESCRIPTION
**Pull request by StCyr**
* Resolves: #157 
* Target version: master 

### Summary

See #157

### CODE REVIEW

**Comment by daita** [comment]
It is working slightly too much !

If I just type the Social Account of the recipient, without validating by pressing 'Enter' when the pop-in with the searched account shows up, I cannot post.

issue_recipients

**Comment by StCyr** [comment]
> If I just type the Social Account of the recipient, without validating by pressing 'Enter' when the pop-in with the searched account shows up, I cannot post.

Ok, maybe I can validate automaticaly when there's only one account found and the user gets out of the tribute component without pressing 'Enter'....

**Comment by StCyr** [comment]
> Ok, maybe I can validate automaticaly when there's only one account found and the user gets out of the tribute component without pressing 'Enter'....

Fixed: spacebar now works as the enter and tab keys.

**Comment by StCyr** [comment]
should be good now

**Pull request merged**
