### PR TITLE
Update DeleteInterface.php

### PR DESCRIPTION
**Pull request by rikmeijer**
Fix warning

* Resolves: # 
* Target version: master

### CODE REVIEW

**Comment by daita** [comment]
hello @rikmeijer, nice catch !

However, can you sign your commit ?

**Comment by rikmeijer** [comment]
> hello @rikmeijer, nice catch !
> 
> However, can you sign your commit ?

Sure, however I committed the change directly through the github interface. Should I change that commit (how?) or should I clone, re-commit and create a different pull-request?

**Comment by rikmeijer** [comment]
Ok, I clone and re(force)pushed the commit, it uses my PGP key now. Ok for you?

**Comment by daita** [comment]
i'll make it ok :)

**Comment by MorrisJobke** [comment]
> The backport to alpha1 failed. Please do this backport manually.

@daita 🏓

**Pull request merged**
