### PR TITLE
0.1.1

### PR DESCRIPTION
**Pull request by daita**
New version and Changelog.

### CODE REVIEW

**Comment by jancborchardt** [comment]
I guess this is blocked by https://github.com/nextcloud/social/pull/255 ?

Also @daita please sign your commits! Check is failing. :)

`git commit --amend -s`

**Comment by daita** [comment]
Why do I see my commit as signed ?

`Signed-off-by: Maxence Lange <maxence@artificial-owl.com>`

**Comment by jancborchardt** [comment]
@daita ah I’m stupid! The "commit signing" in the branch protection refers to GPG signing apparently: https://help.github.com/articles/about-commit-signature-verification/

Disabled it in the branch protection settings, sorry for the noise. :)

**Comment by jancborchardt** [comment]
Seems we actually need to add the DCO status check instead. cc @MorrisJobke @rullzer for help there.

**Comment by juliushaertl** [comment]
@daita But it doesn't hurt to sign the commits as well :wink:

**Pull request merged**
