### PR TITLE
Add cypress testing

### PR DESCRIPTION
**Pull request by juliushaertl**

### CODE REVIEW

**Comment by juliushaertl** [comment]
Unassigned myself again since I will not have time for this any time soon. Feel free to close or adapt to how it is done in viewer for the server setup https://github.com/nextcloud/viewer/tree/master/cypress

**Comment by icewind1991** [comment]
reworked it based on the setup of the viewer app

**Comment by juliushaertl** [comment]
Seems good to me now. Probably needs the cypress secret to be updated in the repo to appear at https://dashboard.cypress.io/projects/7mqhfh/

**Comment by icewind1991** [comment]
Ok, lets merge and we can fix the secret afterwards

**Comment by juliushaertl** [comment]
Added it to the repo and retriggered the CI job, let's see

**Pull request merged**
