### PR TITLE
Add the ability to follow from external website

### PR DESCRIPTION
**Pull request by daita**
related to #268

Implementation of OStatus (it seems to work like this):

- the remote website open a page (in popup) from the app, with the remote account in params.
- in the opened popup, we display the result of a search on the remote account set in params. We display also a 'Follow' button.
- if user is not authed, login/password.

ToDo:
- [x] Implement popup for following external accounts
- [x] Open popover to follow from public pages

## Follow from a public mastodon page
image

image

### Follow with a remote account from public profile pages:

image

### CODE REVIEW

**Comment by daita** [comment]
[Result](https://giant.gfycat.com/AccurateChiefJoey.mp4)

@juliushaertl can you fill the popup with the result of a search of the account set in the controller ?
Maybe the popup should close after a click on 'Follow'.

**Comment by juliushaertl** [comment]
First part is done, the popup content when trying to follow a remote account with your nextcloud social account:

image

**Comment by daita** [comment]
You're saying the first part, what is the second part ?

I mean, once you click on Follow, the popup is closed and we're good.

**Comment by juliushaertl** [comment]
@daita The second part was to have the popup on public pages. Please test and review ;)

**Comment by juliushaertl** [comment]
@jancborchardt Please have a look as well, I've added some screenshots to the first post.

**Comment by daita** [comment]
I will check asap, I can't wait to see how it fit with my theming !

**Comment by daita** [comment]
selection_062

Nice ! just that the content is _slightly_ bigger than the default popup created by mastodon

**Comment by daita** [comment]
I would approve this PRs if I could !

@juliushaertl  : can you rebase and check the conflicting file ?

**Pull request merged**
