### PR TITLE
Add UI to reply to a post and delete

### LINKED ISSUE #155: Delete your own post
We need to add a way to delete  your own post on the UI, and manage this on the back-end

### LINKED ISSUE #158: [UI] Ability to reply to a Post.
Theoretically, the back-end is already able to do that, an implementation on the UI should be enough. The idea is to fill the 'replyTo' field with the Id of the original post during the creation of the Post

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #158 
Fixes #155

image

### CODE REVIEW

**Comment by jancborchardt** [comment]
Replying should be outside of the 3-dot menu (much like Favorite and Repost in the future) as it’s a core action of the app. Should be an icon with text below the post text, like on Mastodon etc.

As icon, the reply arrow is good (which you use in the embed too)  and as text "Reply" is enough. (Not the comment icon and "Reply to post" as in the menu. :)

**Comment by jancborchardt** [comment]
Also – wow, very nice! :balloon: Wasn’t expecting this already now, great work @juliushaertl!

**Comment by juliushaertl** [comment]
@jancborchardt 
image

**Comment by daita** [comment]
Thanks for this report, i'll have a look on a fresh install

**Comment by daita** [comment]
> looks nice!
> however:
> 
>     * the three dot menu is also shown on posts from other people where deletion is not possible and it's empty therefore... we shouldn't show the three dots if there is no option in it:
>       image
> 

Confirming this issue, empty box under the arrow. @juliushaertl 

>     * also I get some js console errors, but that's probably an issue on my side with the backend; occ social:cache:refresh throws an unhandled exeption `Error: Call to a member function blindKeyRotation() on null in /home/jonas/nextcloud/apps/social/lib/Command/CacheRefresh.php:112`
> 
>     * I also can't see the reply posts anywhere

There is some issue with the actor_info, you might see something about it in your JS console: #404 
The issue with the CacheRefresh is not from this PR. I am working on this.

**Comment by jancborchardt** [comment]
Looks nice @juliushaertl – only the menu is now left-aligned, should be centered below the 3-dot icon like before. :)

**Comment by violoncelloCH** [comment]
I'm also wondering if there should be any kind of indication in the timeline that one post is a reply to another... or will this be done in a following PR?
for me replies look like normal posts and are added at the top of the timeline

**Comment by daita** [comment]
no; but you're right that this should be implemented (in another PRs)

**Comment by juliushaertl** [comment]
@jancborchardt Adressed your comments, this is what it looks like now:

image

**Comment by daita** [comment]
@juliushaertl  : if you don't want to quickly fix the last issue reported by @violoncelloCH, we can we merge and create a bug report for later !

**Comment by daita** [comment]
merging, so it will be easier to work on the boost option #374

**Pull request merged**
