### PR TITLE
linked data signature

### PR DESCRIPTION
**Pull request by daita**
#199 - In case of a remote instance just bounce an object create from a 3rd instance.

We're using https://w3c-dvcg.github.io/ld-signatures to verify and sign objects so we can check their content

If available, the origin of the signed content is use to check the validity of the content. If not available, we keep using the origin from the header of the request.

### CODE REVIEW

**Comment by daita** [comment]
To test this PR, a `make composer` is mandatory !

**Comment by jancborchardt** [comment]
> To test this PR, a `make composer` is mandatory !

Will this be mandatory for everything from this point on? If so, please add it to the readme. :)

**Comment by daita** [comment]
This is now done. The signing and verifying process have been tested this way:

- UserA (Social App) follows UserB (Mastodon)
- UserC (Social App) follows UserB.
- UserC reply to a post from UserB and sign it.
- UserA receive the post and verify the origin.

**Comment by juliushaertl** [comment]
Rebased to master.

**Pull request merged**
