### PR TITLE
Make CI happy

### PR DESCRIPTION
**Pull request by juliushaertl**
As green ci is much nicer to have :wink:

### CODE REVIEW

**Comment by juliushaertl** [comment]
>  we should probably also test on something newer than php 7.1 and NC 17, right? (but this can obviously be a separate PR) 

Ideally there would also be tests, because as of right now it only checks if the app can be enabled properly. :grin:

**Comment by violoncelloCH** [comment]
should I create issues for this or we won't forget anyway?

**Comment by daita** [comment]
you should create an issue

**Comment by violoncelloCH** [comment]
here you go: #921 & #922

**Pull request merged**
