### PR TITLE
Delete Note from db if author is no more in cache

### PR DESCRIPTION
**Pull request by daita**
This is an hotfix for the missing actor_info on the front-end.

We should also remove the Notes when the author is deleted from a remote instance.

### CODE REVIEW

**Comment by daita** [comment]
I don't like this solution. **This will not be merged.**  (you can still use this branch to delete bogus entries by reloading the app)

I think the front-end should just check if actor_info exists or not, as the data from actor_info is used just to display the right avatar. If no actor_info, no avatar.

The faulty entries will be managed by a background process.

**Comment by violoncelloCH** [comment]
@daita I've done a complete reset of the app and now I can't reproduce the actor_info console error, so I can't test this...

**Comment by daita** [comment]
If you want to reproduce the issue to help you fixing fix it on the front-end: you need to delete an entry from the cache_actors database. The deleted entry needs to be an author of a Note.

**Comment by juliushaertl** [comment]
Replaced by #412

**Pull request closed without merging**
